# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YtDownloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 558)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QProgressBar {\n"
"    border: 2px solid rgb(16, 16, 16);\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(242, 128, 133); \n"
"    width: 20px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TreakDownloadList = QtWidgets.QTableView(self.centralwidget)
        self.TreakDownloadList.setStyleSheet("QTableView {\n"
"    color: white;\n"
"    gridline-color:white; \n"
"    border-color: rgb(242, 128, 133); \n"
"    background-color:rgb(16, 16, 16);\n"
"    selection-background-color:  rgb(183,46,43);\n"
"    outline: 0;\n"
"    show-decoration-selected: 0; /* make the selection span the entire width of the view */\n"
"}\n"
"QHeaderView::section {\n"
"    background-color:rgb(42, 42, 42);\n"
"    color: white;\n"
"    height: 35px;\n"
"    width: 150px; \n"
"    color: white;\n"
"   \n"
"}\n"
"QTableView::item:focus{\n"
"    color: white;\n"
"}\n"
"\n"
"QTableView QProgressBar {\n"
"    border: 2px solid rgb(16, 16, 16);\n"
"}\n"
"\n"
"QTableView QProgressBar::chunk {\n"
"    background-color: rgb(242, 128, 133); \n"
"    width: 20px;\n"
"}\n"
"")
        self.TreakDownloadList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TreakDownloadList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.TreakDownloadList.setAlternatingRowColors(False)
        self.TreakDownloadList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TreakDownloadList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TreakDownloadList.setShowGrid(True)
        self.TreakDownloadList.setObjectName("TreakDownloadList")
        self.TreakDownloadList.horizontalHeader().setHighlightSections(False)
        self.TreakDownloadList.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.TreakDownloadList)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MSMP Downloader"))
