# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitledSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MSMPsettings(object):
    def setupUi(self, MSMPsettings):
        MSMPsettings.setObjectName("MSMPsettings")
        MSMPsettings.setEnabled(True)
        MSMPsettings.resize(800, 613)
        MSMPsettings.setMinimumSize(QtCore.QSize(800, 613))
        MSMPsettings.setMaximumSize(QtCore.QSize(800, 613))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MSMPsettings.setWindowIcon(icon)
        MSMPsettings.setStyleSheet("")
        MSMPsettings.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(MSMPsettings)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainBox = QtWidgets.QGroupBox(MSMPsettings)
        self.MainBox.setStyleSheet("QGroupBox{\n"
"    background-color:rgb(17, 17, 17);\n"
"    color:white;\n"
"}")
        self.MainBox.setObjectName("MainBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.MainBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"   background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0686275 rgba(255, 0, 4, 255), stop:0.392157 rgba(0, 0, 0, 0));\n"
"   color:rgb(255,255,255);\n"
"   border-bottom: 100px solid;\n"
"   border-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0686275 rgba(255, 0, 4, 255), stop:0.392157 rgba(0, 0, 0, 0));\n"
"}")
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Belarus))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("qMSMP Stream")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.SettingsMenuMain = QtWidgets.QGroupBox(self.MainBox)
        self.SettingsMenuMain.setObjectName("SettingsMenuMain")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.SettingsMenuMain)
        self.horizontalLayout.setContentsMargins(1, -1, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView = QtWidgets.QListView(self.SettingsMenuMain)
        self.listView.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listView.setStyleSheet("QListView{\n"
"   background-color:rgb(21,21, 21);\n"
"   color:rgb(255,255,255);\n"
"\n"
"   border:none;\n"
"   border-bottom: 1px solid;\n"
"}")
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setProperty("showDropIndicator", False)
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.listView)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.SettingsMenuMain)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    background-color: rgb(17, 17, 17);\n"
"    color:white;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_lastfm = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_lastfm.setStyleSheet("QCheckBox{\n"
"    color:white;\n"
"}")
        self.checkBox_lastfm.setObjectName("checkBox_lastfm")
        self.horizontalLayout_2.addWidget(self.checkBox_lastfm)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.LogoutLastFm = QtWidgets.QPushButton(self.groupBox)
        self.LogoutLastFm.setStyleSheet("QPushButton {\n"
"    background-color:rgb(42, 42, 42);\n"
"    border-width: 1px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    min-width: 7em;\n"
"    padding: 5px;\n"
"    color:white;\n"
"\n"
"}")
        self.LogoutLastFm.setObjectName("LogoutLastFm")
        self.horizontalLayout_2.addWidget(self.LogoutLastFm)
        self.LoginLastFmButton = QtWidgets.QPushButton(self.groupBox)
        self.LoginLastFmButton.setStyleSheet("QPushButton {\n"
"    background-color:rgb(42, 42, 42);\n"
"    border-width: 1px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    min-width: 7em;\n"
"    padding: 5px;\n"
"    color:white;\n"
"\n"
"}")
        self.LoginLastFmButton.setObjectName("LoginLastFmButton")
        self.horizontalLayout_2.addWidget(self.LoginLastFmButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.checkBox_Discord = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Discord.setStyleSheet("QCheckBox{\n"
"    color:white;\n"
"}")
        self.checkBox_Discord.setObjectName("checkBox_Discord")
        self.verticalLayout_6.addWidget(self.checkBox_Discord)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.SettingsMenuMain)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.checkBox_DisablePlaylists = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_DisablePlaylists.setStyleSheet("QCheckBox{\n"
"    color:white;\n"
"}")
        self.checkBox_DisablePlaylists.setObjectName("checkBox_DisablePlaylists")
        self.verticalLayout_7.addWidget(self.checkBox_DisablePlaylists)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setStyleSheet("QLabel{\n"
"    color:white;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.SelectFolderDownloadLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.SelectFolderDownloadLineEdit.setStyleSheet("QLineEdit{\n"
"   background-color:rgb(0,0, 0);\n"
"   color:rgb(255,255,255);\n"
"   border:none;\n"
"   border-bottom: 1px solid;\n"
"\n"
"}")
        self.SelectFolderDownloadLineEdit.setObjectName("SelectFolderDownloadLineEdit")
        self.horizontalLayout_4.addWidget(self.SelectFolderDownloadLineEdit)
        self.SelectFolderDownloadButton = QtWidgets.QPushButton(self.groupBox_2)
        self.SelectFolderDownloadButton.setStyleSheet("QPushButton {\n"
"    background-color:rgb(42, 42, 42);\n"
"    border-width: 1px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    min-width: 7em;\n"
"    padding: 5px;\n"
"    color:white;\n"
"\n"
"}")
        self.SelectFolderDownloadButton.setObjectName("SelectFolderDownloadButton")
        self.horizontalLayout_4.addWidget(self.SelectFolderDownloadButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setStyleSheet("QLabel{\n"
"    color:white;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.SelectFolderPlaylistLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.SelectFolderPlaylistLineEdit.setStyleSheet("QLineEdit{\n"
"   background-color:rgb(0,0, 0);\n"
"   color:rgb(255,255,255);\n"
"   border:none;\n"
"   border-bottom: 1px solid;\n"
"\n"
"}")
        self.SelectFolderPlaylistLineEdit.setObjectName("SelectFolderPlaylistLineEdit")
        self.horizontalLayout_5.addWidget(self.SelectFolderPlaylistLineEdit)
        self.SelectFolderPlaylistButton = QtWidgets.QPushButton(self.groupBox_2)
        self.SelectFolderPlaylistButton.setStyleSheet("QPushButton {\n"
"    background-color:rgb(42, 42, 42);\n"
"    border-width: 1px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    min-width: 7em;\n"
"    padding: 5px;\n"
"    color:white;\n"
"\n"
"}")
        self.SelectFolderPlaylistButton.setObjectName("SelectFolderPlaylistButton")
        self.horizontalLayout_5.addWidget(self.SelectFolderPlaylistButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setStyleSheet("QLabel{\n"
"    color:white;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.TOKENvkMusicLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.TOKENvkMusicLineEdit.setStyleSheet("QLineEdit{\n"
"   background-color:rgb(0,0, 0);\n"
"   color:rgb(255,255,255);\n"
"   border:none;\n"
"   border-bottom: 1px solid;\n"
"\n"
"}")
        self.TOKENvkMusicLineEdit.setObjectName("TOKENvkMusicLineEdit")
        self.horizontalLayout_6.addWidget(self.TOKENvkMusicLineEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setStyleSheet("QLabel{\n"
"    color:white;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.YandexMusicLineEdit_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.YandexMusicLineEdit_lineEdit.setStyleSheet("QLineEdit{\n"
"   background-color:rgb(0,0, 0);\n"
"   color:rgb(255,255,255);\n"
"   border:none;\n"
"   border-bottom: 1px solid;\n"
"\n"
"}")
        self.YandexMusicLineEdit_lineEdit.setObjectName("YandexMusicLineEdit_lineEdit")
        self.horizontalLayout_7.addWidget(self.YandexMusicLineEdit_lineEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.SettingsMenuMain)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_Equalizer = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_Equalizer.setObjectName("checkBox_Equalizer")
        self.verticalLayout_5.addWidget(self.checkBox_Equalizer)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.EqualizerSlider_1 = QtWidgets.QSlider(self.groupBox_3)
        self.EqualizerSlider_1.setMinimum(-200)
        self.EqualizerSlider_1.setMaximum(200)
        self.EqualizerSlider_1.setPageStep(1)
        self.EqualizerSlider_1.setTracking(True)
        self.EqualizerSlider_1.setOrientation(QtCore.Qt.Vertical)
        self.EqualizerSlider_1.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.EqualizerSlider_1.setTickInterval(0)
        self.EqualizerSlider_1.setObjectName("EqualizerSlider_1")
        self.horizontalLayout_8.addWidget(self.EqualizerSlider_1)
        self.EqualizerSlider_2 = QtWidgets.QSlider(self.groupBox_3)
        self.EqualizerSlider_2.setMinimum(-200)
        self.EqualizerSlider_2.setMaximum(200)
        self.EqualizerSlider_2.setPageStep(1)
        self.EqualizerSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.EqualizerSlider_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.EqualizerSlider_2.setObjectName("EqualizerSlider_2")
        self.horizontalLayout_8.addWidget(self.EqualizerSlider_2)
        self.EqualizerSlider_3 = QtWidgets.QSlider(self.groupBox_3)
        self.EqualizerSlider_3.setMinimum(-200)
        self.EqualizerSlider_3.setMaximum(200)
        self.EqualizerSlider_3.setPageStep(1)
        self.EqualizerSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.EqualizerSlider_3.setInvertedControls(False)
        self.EqualizerSlider_3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.EqualizerSlider_3.setObjectName("EqualizerSlider_3")
        self.horizontalLayout_8.addWidget(self.EqualizerSlider_3)
        self.EqualizerSlider_4 = QtWidgets.QSlider(self.groupBox_3)
        self.EqualizerSlider_4.setMinimum(-200)
        self.EqualizerSlider_4.setMaximum(200)
        self.EqualizerSlider_4.setPageStep(1)
        self.EqualizerSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.EqualizerSlider_4.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.EqualizerSlider_4.setObjectName("EqualizerSlider_4")
        self.horizontalLayout_8.addWidget(self.EqualizerSlider_4)
        self.EqualizerSlider_5 = QtWidgets.QSlider(self.groupBox_3)
        self.EqualizerSlider_5.setMinimum(-200)
        self.EqualizerSlider_5.setMaximum(200)
        self.EqualizerSlider_5.setPageStep(1)
        self.EqualizerSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.EqualizerSlider_5.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.EqualizerSlider_5.setObjectName("EqualizerSlider_5")
        self.horizontalLayout_8.addWidget(self.EqualizerSlider_5)
        self.EqualizerSlider_6 = QtWidgets.QSlider(self.groupBox_3)
        self.EqualizerSlider_6.setMinimum(-200)
        self.EqualizerSlider_6.setMaximum(200)
        self.EqualizerSlider_6.setPageStep(1)
        self.EqualizerSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.EqualizerSlider_6.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.EqualizerSlider_6.setObjectName("EqualizerSlider_6")
        self.horizontalLayout_8.addWidget(self.EqualizerSlider_6)
        self.EqualizerSlider_7 = QtWidgets.QSlider(self.groupBox_3)
        self.EqualizerSlider_7.setMinimum(-200)
        self.EqualizerSlider_7.setMaximum(200)
        self.EqualizerSlider_7.setPageStep(1)
        self.EqualizerSlider_7.setOrientation(QtCore.Qt.Vertical)
        self.EqualizerSlider_7.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.EqualizerSlider_7.setObjectName("EqualizerSlider_7")
        self.horizontalLayout_8.addWidget(self.EqualizerSlider_7)
        self.EqualizerSlider_8 = QtWidgets.QSlider(self.groupBox_3)
        self.EqualizerSlider_8.setMinimum(-200)
        self.EqualizerSlider_8.setMaximum(200)
        self.EqualizerSlider_8.setPageStep(1)
        self.EqualizerSlider_8.setOrientation(QtCore.Qt.Vertical)
        self.EqualizerSlider_8.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.EqualizerSlider_8.setObjectName("EqualizerSlider_8")
        self.horizontalLayout_8.addWidget(self.EqualizerSlider_8)
        self.EqualizerSlider_9 = QtWidgets.QSlider(self.groupBox_3)
        self.EqualizerSlider_9.setMinimum(-200)
        self.EqualizerSlider_9.setMaximum(200)
        self.EqualizerSlider_9.setPageStep(1)
        self.EqualizerSlider_9.setOrientation(QtCore.Qt.Vertical)
        self.EqualizerSlider_9.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.EqualizerSlider_9.setObjectName("EqualizerSlider_9")
        self.horizontalLayout_8.addWidget(self.EqualizerSlider_9)
        self.EqualizerSlider_10 = QtWidgets.QSlider(self.groupBox_3)
        self.EqualizerSlider_10.setMinimum(-200)
        self.EqualizerSlider_10.setMaximum(200)
        self.EqualizerSlider_10.setPageStep(1)
        self.EqualizerSlider_10.setOrientation(QtCore.Qt.Vertical)
        self.EqualizerSlider_10.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.EqualizerSlider_10.setObjectName("EqualizerSlider_10")
        self.horizontalLayout_8.addWidget(self.EqualizerSlider_10)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.EqualizerSlider_11 = QtWidgets.QSlider(self.groupBox_3)
        self.EqualizerSlider_11.setMinimum(-200)
        self.EqualizerSlider_11.setMaximum(200)
        self.EqualizerSlider_11.setOrientation(QtCore.Qt.Vertical)
        self.EqualizerSlider_11.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.EqualizerSlider_11.setObjectName("EqualizerSlider_11")
        self.horizontalLayout_8.addWidget(self.EqualizerSlider_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(10, -1, 19, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.EqualizerIndicator_1 = QtWidgets.QLabel(self.groupBox_3)
        self.EqualizerIndicator_1.setAlignment(QtCore.Qt.AlignCenter)
        self.EqualizerIndicator_1.setObjectName("EqualizerIndicator_1")
        self.horizontalLayout_10.addWidget(self.EqualizerIndicator_1)
        self.EqualizerIndicator_2 = QtWidgets.QLabel(self.groupBox_3)
        self.EqualizerIndicator_2.setAlignment(QtCore.Qt.AlignCenter)
        self.EqualizerIndicator_2.setObjectName("EqualizerIndicator_2")
        self.horizontalLayout_10.addWidget(self.EqualizerIndicator_2)
        self.EqualizerIndicator_3 = QtWidgets.QLabel(self.groupBox_3)
        self.EqualizerIndicator_3.setAlignment(QtCore.Qt.AlignCenter)
        self.EqualizerIndicator_3.setObjectName("EqualizerIndicator_3")
        self.horizontalLayout_10.addWidget(self.EqualizerIndicator_3)
        self.EqualizerIndicator_4 = QtWidgets.QLabel(self.groupBox_3)
        self.EqualizerIndicator_4.setAlignment(QtCore.Qt.AlignCenter)
        self.EqualizerIndicator_4.setObjectName("EqualizerIndicator_4")
        self.horizontalLayout_10.addWidget(self.EqualizerIndicator_4)
        self.EqualizerIndicator_5 = QtWidgets.QLabel(self.groupBox_3)
        self.EqualizerIndicator_5.setAlignment(QtCore.Qt.AlignCenter)
        self.EqualizerIndicator_5.setObjectName("EqualizerIndicator_5")
        self.horizontalLayout_10.addWidget(self.EqualizerIndicator_5)
        self.EqualizerIndicator_6 = QtWidgets.QLabel(self.groupBox_3)
        self.EqualizerIndicator_6.setAlignment(QtCore.Qt.AlignCenter)
        self.EqualizerIndicator_6.setObjectName("EqualizerIndicator_6")
        self.horizontalLayout_10.addWidget(self.EqualizerIndicator_6)
        self.EqualizerIndicator_7 = QtWidgets.QLabel(self.groupBox_3)
        self.EqualizerIndicator_7.setAlignment(QtCore.Qt.AlignCenter)
        self.EqualizerIndicator_7.setObjectName("EqualizerIndicator_7")
        self.horizontalLayout_10.addWidget(self.EqualizerIndicator_7)
        self.EqualizerIndicator_8 = QtWidgets.QLabel(self.groupBox_3)
        self.EqualizerIndicator_8.setAlignment(QtCore.Qt.AlignCenter)
        self.EqualizerIndicator_8.setObjectName("EqualizerIndicator_8")
        self.horizontalLayout_10.addWidget(self.EqualizerIndicator_8)
        self.EqualizerIndicator_9 = QtWidgets.QLabel(self.groupBox_3)
        self.EqualizerIndicator_9.setAlignment(QtCore.Qt.AlignCenter)
        self.EqualizerIndicator_9.setObjectName("EqualizerIndicator_9")
        self.horizontalLayout_10.addWidget(self.EqualizerIndicator_9)
        self.EqualizerIndicator_10 = QtWidgets.QLabel(self.groupBox_3)
        self.EqualizerIndicator_10.setAlignment(QtCore.Qt.AlignCenter)
        self.EqualizerIndicator_10.setObjectName("EqualizerIndicator_10")
        self.horizontalLayout_10.addWidget(self.EqualizerIndicator_10)
        spacerItem4 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.EqualizerIndicator_11 = QtWidgets.QLabel(self.groupBox_3)
        self.EqualizerIndicator_11.setAlignment(QtCore.Qt.AlignCenter)
        self.EqualizerIndicator_11.setObjectName("EqualizerIndicator_11")
        self.horizontalLayout_10.addWidget(self.EqualizerIndicator_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        spacerItem5 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupbox_4 = QtWidgets.QGroupBox(self.SettingsMenuMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_4.sizePolicy().hasHeightForWidth())
        self.groupbox_4.setSizePolicy(sizePolicy)
        self.groupbox_4.setStyleSheet("QGroupBox{\n"
"    background: rgb(39, 39, 39)\n"
"   \n"
"}")
        self.groupbox_4.setObjectName("groupbox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupbox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupbox_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        self.ExampleImg = QtWidgets.QFrame(self.groupbox_4)
        self.ExampleImg.setMinimumSize(QtCore.QSize(432, 324))
        self.ExampleImg.setMaximumSize(QtCore.QSize(432, 324))
        self.ExampleImg.setStyleSheet("QFrame{\n"
"  border: none;\n"
"  border-image: url(img/MSMPimgExample.png);\n"
"  background: rgb(255, 0,0)\n"
"}\n"
"")
        self.ExampleImg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ExampleImg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ExampleImg.setObjectName("ExampleImg")
        self.horizontalLayout_9.addWidget(self.ExampleImg)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.verticalLayout_3.addWidget(self.groupbox_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.SettingsMenuMain)
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.MainBox)
        self.horizontalGroupBox.setStyleSheet("QGroupBox{\n"
"   background-color:rgb(188, 30, 30);\n"
"   color:rgb(255,255,255);\n"
"\n"
"   border:none;\n"
"   border-bottom: 1px solid;\n"
"}")
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout_3.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ButtonBox = QtWidgets.QDialogButtonBox(self.horizontalGroupBox)
        self.ButtonBox.setMinimumSize(QtCore.QSize(0, 35))
        self.ButtonBox.setStyleSheet("QDialogButtonBox > QPushButton {\n"
"    background-color:rgb(42, 42, 42);\n"
"    /*border-style: outset;*/\n"
"    border-width: 1px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    min-width: 7em;\n"
"    padding: 5px;\n"
"    color:white;\n"
"\n"
"}")
        self.ButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.ButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ButtonBox.setCenterButtons(False)
        self.ButtonBox.setObjectName("ButtonBox")
        self.horizontalLayout_3.addWidget(self.ButtonBox)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox)
        self.verticalLayout.addWidget(self.MainBox)

        self.retranslateUi(MSMPsettings)
        QtCore.QMetaObject.connectSlotsByName(MSMPsettings)

    def retranslateUi(self, MSMPsettings):
        _translate = QtCore.QCoreApplication.translate
        MSMPsettings.setWindowTitle(_translate("MSMPsettings", "MSMPsettings"))
        self.groupBox.setTitle(_translate("MSMPsettings", "Интеграции"))
        self.checkBox_lastfm.setText(_translate("MSMPsettings", "LastFM"))
        self.LogoutLastFm.setText(_translate("MSMPsettings", "выйти"))
        self.LoginLastFmButton.setText(_translate("MSMPsettings", "войти в LastFM"))
        self.checkBox_Discord.setText(_translate("MSMPsettings", "Discord RPC"))
        self.groupBox_2.setTitle(_translate("MSMPsettings", "Параметры"))
        self.checkBox_DisablePlaylists.setText(_translate("MSMPsettings", "Папка Плейлистов"))
        self.label_2.setText(_translate("MSMPsettings", "Папка скаченных треков: "))
        self.SelectFolderDownloadButton.setText(_translate("MSMPsettings", "Выбрать"))
        self.label_3.setText(_translate("MSMPsettings", "Папка плейлистов: "))
        self.SelectFolderPlaylistButton.setText(_translate("MSMPsettings", "Выбрать"))
        self.label_4.setText(_translate("MSMPsettings", "TOKENvkMusic: "))
        self.label_5.setText(_translate("MSMPsettings", "YandexMusicTOKEN: "))
        self.groupBox_3.setTitle(_translate("MSMPsettings", "Экволайзер"))
        self.checkBox_Equalizer.setText(_translate("MSMPsettings", "Включён"))
        self.EqualizerIndicator_1.setText(_translate("MSMPsettings", "0"))
        self.EqualizerIndicator_2.setText(_translate("MSMPsettings", "0"))
        self.EqualizerIndicator_3.setText(_translate("MSMPsettings", "0"))
        self.EqualizerIndicator_4.setText(_translate("MSMPsettings", "0"))
        self.EqualizerIndicator_5.setText(_translate("MSMPsettings", "0"))
        self.EqualizerIndicator_6.setText(_translate("MSMPsettings", "0"))
        self.EqualizerIndicator_7.setText(_translate("MSMPsettings", "0"))
        self.EqualizerIndicator_8.setText(_translate("MSMPsettings", "0"))
        self.EqualizerIndicator_9.setText(_translate("MSMPsettings", "0"))
        self.EqualizerIndicator_10.setText(_translate("MSMPsettings", "0"))
        self.EqualizerIndicator_11.setText(_translate("MSMPsettings", "0"))
        self.groupbox_4.setTitle(_translate("MSMPsettings", "Персонализация"))
        self.pushButton_2.setText(_translate("MSMPsettings", "ChangeColor"))
